# Generated by Django 5.2.4 on 2025-07-24 17:00

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="video",
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="posts/images/",
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
            ),
        ),
    ]
