# Generated by Django 5.2.4 on 2025-07-25 00:05

import api.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_is_edited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
                verbose_name="image",
            ),
        ),
    ]
