# Generated by Django 5.2.4 on 2025-07-24 17:00

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/cover_photos/",
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profile_pictures/",
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
            ),
        ),
    ]
