# Generated by Django 5.2.4 on 2025-07-25 00:05

import api.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_cover_photo_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    api.validators.validate_file_size,
                    api.validators.validate_image_format,
                ],
                verbose_name="image",
            ),
        ),
    ]
