# Generated by Django 5.2.4 on 2025-09-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_cover_photo_alter_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_pro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="pro_subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="pro_subscription_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
